### ISSUE TITLE
sprig-reap broke the yaml formatting

### ISSUE THREAD

**Issue by alexanderadam** [vigetlabs/sprig-reap#11]
I already hat a sprig definition with the structure

```YAML
options:
  find_existing_by: ['identifier']

records:
  - sprig_id: 1
    identifier: lorem
  - sprig_id: 2
    identifier: ipsum
```

After using `sprig-reap` the structure was

```YAML
options:
  find_existing_by: ['identifier']

records:
  - sprig_id: 1
    identifier: lorem
  - sprig_id: 2
    identifier: ipsum

- sprig_id: 3
  identifier: dolor
- sprig_id: 3
  identifier: sit
```

So there was wrong indention ([the duplicated id is already mentioned in another issue](https://github.com/vigetlabs/sprig-reap/issues/10))
